### ISSUE TITLE
GTK-theme

### ISSUE THREAD

**Issue by karambaq** [NerdyPepper/dotfiles#3]
Hi, where can I find your gtk theme?

**Comment by oppiliappan** [comment]
I dont upload my GTK theme to my dotfles.

It can be easily recreated with [oomox](https://github.com/actionless/oomox).

**Comment by karambaq** [comment]
Is it too hard to share? Or tell me the colors.

**Comment by oppiliappan** [comment]
You can now find my GTK themes in the [oomox ](https://github.com/actionless/oomox/) application as of this [commit](https://github.com/actionless/oomox/commit/2d260b1e0ca6228ec7f0947a73659cdfa746afbf).

I dont usually keep my GTK themes in my dotfiles repo, because I see no need to back them up for later use :D
